/* version.h file expanded by Cmake for build */

#ifndef VERSION_H
#define VERSION_H

#define NTIRPC_VERSION_MAJOR @NTIRPC_MAJOR_VERSION@
#define NTIRPC_VERSION_MINOR @NTIRPC_MINOR_VERSION@
#define NTIRPC_PATCH_LEVEL @NTIRPC_PATCH_LEVEL@

#define NTIRPC_VERSION "@NTIRPC_MAJOR_VERSION@.@NTIRPC_MINOR_VERSION@.@NTIRPC_PATCH_LEVEL@"
#define NTIRPC_VERSION_COMMENT "@VERSION_COMMENT@"
#define _GIT_HEAD_COMMIT "@_GIT_HEAD_COMMIT@"
#define _GIT_DESCRIBE "@_GIT_DESCRIBE@"

#endif /* VERSION_H */
